### ISSUE TITLE
ADSR.decayTime() returns "nan"

### ISSUE THREAD

**Issue by jpyepez** [ccrma/chuck#116]
*Environment:*
Chuck 1.4 (numchucks)
Mac OS X High Sierra

*Description:*
I noticed that the function decayTime() is not returning a valid duration value at the moment. In the following minimum working example:

```chuck
SinOsc sin => ADSR env => dac;
env.set(second, second, 1., second);

<<< "Attack Time: ", env.attackTime() >>>;
<<< "Decay Time: ", env.decayTime() >>>;
<<< "Sustain Level: ", env.sustainLevel() >>>;
<<< "Release Time: ", env.releaseTime() >>>;
```

*Expected result:* 
env.decayTime() returns the current envelope decay time as a valid dur.

*Result:* 
env.decayTime() returns "nan". Seems to be the only envelope getter to be broken at the moment.

![2018-03-10_04-30-28](https://user-images.githubusercontent.com/9814036/37215081-d3009c0c-241b-11e8-827a-3d1bbfca0e0d.png)

**Comment by yuanyelele** [comment]
core/ugen_stk.cpp: line 4977
void ADSR :: setDecayTime(MY_FLOAT aTime)
``  else decayRate = (1.0 - sustainLevel) / ( aTime * Stk::sampleRate() );

core/ugen_stk.cpp: line 4998
MY_FLOAT ADSR :: getDecayTime()
`` { return (1.0 - sustainLevel) / (decayRate*Stk::sampleRate()); }

If sustainLevel is 1, decayRate is 0, hence the "nan"

**Comment by mariobuoninfante** [comment]
proposed a solution in #144

**Comment by gewang** [comment]
Thank you and sorry for the long-standing bug. Based on @mariobuoninfante's attention and fix, we combed through ADSR to address the situations when sustain is either 1 or 0 and also made things hopefully more robust to various edge cases. The changes were pushed as of 20d717e and will be incorporated in 1.4.0.2. Please feel free to stress test this more.  Thank you again!
