### ISSUE TITLE
Impossible to reset Gen10 coeffs

### ISSUE THREAD

**Issue by mariobuoninfante** [ccrma/chuck#119]
It's not possible to reset Gen10 coefficients once they've been initialized

I had a quick look at the source code (ugen_osc.cpp, row 1469) and the possibility of having a coefficient equal to 0 is not considered.

Would it be better if we could remove partials?

**Comment by gewang** [comment]
Thank you for the fix to this issue. It has been pushed in 86c58f0 and will be included in 1.4.0.2.
