### ISSUE TITLE
cast from str to int

### ISSUE THREAD

**Issue by inkeye** [ccrma/chuck#121]
First of all thx for creating chuck. It is of great use.

If you try to run: `"1" $ int;` you get `invalid cast to 'int' from 'string'...`

If there is no cast from str to int command line arguments for example are pretty useless in my opinion.

Would be cool if that gets implemented. Maybe I can provide a patch myself If I have time to delve into the code.

Keep up the good work.

**Comment by lathertonj** [comment]
Hi! You are looking for Std.atoi().
http://chuck.cs.princeton.edu/doc/program/stdlib.html

Happy ChucKing!
Jack

**Comment by inkeye** [comment]
Thank you very much.
Didnt spot that page in the documentation.
Sorry for unnecessary issue.
