### ISSUE TITLE
Gen10 issue with odd partials

### ISSUE THREAD

**Issue by mariobuoninfante** [ccrma/chuck#122]
Hi,

It seems like Gen10 has an issue when dealing with odd harmonics (not fundamental).
It's easy to repro taking the example code and using the following coefficients instead:
g10.coefs( [0., 0., 0.5] ); - shows the issue
g10.coefs( [0., 0.5, 0.] ); - doesn't show the issue
Hooking ChucK up to a spectrum analyzer it's easy to see the difference.
In case there are odd harmonics there are a lot of partials/sidebands, instead of having only the components specified in .coefs().
Tested on Ubuntu Studio 16.04 - ChucK 1.4.0

**Comment by mariobuoninfante** [comment]
Gen9 doesn't seem to show the issue

**Comment by mariobuoninfante** [comment]
further testing shows that it's not about the odd harmonics, from the 5th harmonic (6th partials) further, sometimes you get unwanted sidebands with odd harmonics, sometimes with even ones.
I'm monitoring the output (DFT) with Baudline

**Comment by mariobuoninfante** [comment]
the issue seems to be in ugen_osc.cpp at row1472 where we have
`t_CKDOUBLE val = (t_CKDOUBLE) (TWO_PI * (t_CKDOUBLE) i / (genX_tableSize / (j + 1)));`

but should be
`t_CKDOUBLE val = (t_CKDOUBLE) (TWO_PI * (t_CKDOUBLE) i / (genX_tableSize / (t_CKFLOAT) (j + 1)));`

**Comment by gewang** [comment]
Thank you for this fix. It has been incorporated as
`val = (t_CKDOUBLE)( TWO_PI * i / (genX_tableSize/(j+1.0)) );`
pushed in 86c58f0 and will be part of 1.4.0.2.
