### ISSUE TITLE
Communicate with outside word with sockets/pipes etc

### ISSUE THREAD

**Issue by zokrezyl** [ccrma/chuck#127]
Am not sure if the project is alive, but would be interesting to have a feature to communicate (non-blocking) with other processes. I see that STK has some tcp/udp sockets, but that is not exposed in  Chuck. This would be interesting for instance to send buffers to external apps for visualization or so. Maybe there is some chuging for this, but could not find so far.

**Comment by lathertonj** [comment]
In ChucK, people usually use OSC (which goes over UDP in most implementations) to send packets of information to other processes on localhost. That might be inconvenient for something as large as a buffer, but maybe you could do some computation on the buffer in ChucK and then send over higher-level messages to your visualizer.

**Comment by zokrezyl** [comment]
I am aware about OSC. For displaying the samples like in https://github.com/ccrma/sndtools/tree/master/src/sndview for instance not sure what computations I could do to be able to transfer it through OSC.

**Comment by lathertonj** [comment]
Another option if your visualizer is written in C++ is to include the src/core/ folder of ChucK and write the audio callback to run ChucK but also store some results into a buffer that is shared between the graphics and visual threads. E.g. could modify http://soundlab.cs.princeton.edu/software/sndpeek/ to include ChucK and run it from the audio callback.

**Comment by zokrezyl** [comment]
Well, looking for an answer to my question ended up among others reading the code of sndpeek. I had the inspiration you mentioned above, but was just wondering if it would make sense to make sockets part of the language or at least exposed through STK. TCP itself would be bit overkill for realtime application, but UDP would make great job in most cases. 

Will have a look at the original STK code maybe that could inspire me how to expose UDP easily.

Find the RT and simplicity of the language very attractive but wish those little missing building blocks were present.
