### ISSUE TITLE
Not possible to send 1 and 2 bytes MIDI messages on Linux

### ISSUE THREAD

**Issue by mariobuoninfante** [ccrma/chuck#130]
Hi,

I've just found out I'm not able to send any MIDI msg that is smaller (or bigger) than 3 bytes.
No real-time messages, aftertouch and program change.
Every time I try this error gets printed to the console:
[chuck](via RtMidi): RtMidiOut::sendMessage: event parsing error!

I'm able to receive them though.

I'm on Ubuntu Studio 16.04 64bit, running ChucK 1.4.0.0

Cheers,
Mario

**Comment by mariobuoninfante** [comment]
I have a gut feeling that the issue could be happening when the MIDI buffer gets resized (snd_midi_event_resize_buffer - https://github.com/ccrma/chuck/search?q=snd_midi_event_resize_buffer&unscoped_q=snd_midi_event_resize_buffer)
I commented out the code from 1421 to 1425:
  // if ( result < (int)nBytes ) {
  //   errorString_ = "RtMidiOut::sendMessage: event parsing error!";
  //   error( RtMidiError::WARNING );
  //   return;
  // }

and now I can send everything but not MIDI clock. I can send stop, continue, etc. though

**Comment by mariobuoninfante** [comment]
last but not the least, commenting that code out allows me to send SysEx as well :)

**Comment by gewang** [comment]
Thank you @mariobuoninfante for the fix. It's been incorporated in bf52fc1 and will part of 1.4.0.1. hope this does not cause issues on other platforms but this looks like a good progress forward.
