### ISSUE TITLE
String cast from Object crash

### ISSUE THREAD

**Issue by armandiB** [ccrma/chuck#133]
Hello everyone,

Casting an object to a string has chuck crash at once. Something as simple as:
`"a" => Object o;
o $ string;`
Same behavior with references (found that out with an ArrayList of strings during a gig).

Best,
Armand

**Comment by armand-bernardi** [comment]
I assumed string inherited from Object because of static string error, but it's primitive when declaring a reference. Easy workaround anyway.

**Comment by markcerqueira** [comment]
We should add a unit test for this once we fix it.

**Comment by gewang** [comment]
tested in `1.5.2.0` no longer crashing but yields potentially confusing values; migrating to #423
