### ISSUE TITLE
getting 'null' instead of memory address when printing more than 1 reference variable

### ISSUE THREAD

**Issue by mariobuoninfante** [ccrma/chuck#138]
MacOS High Sierra 10.13.1 - ChucK 1.4.0.0

When trying to print a variable reference the following way:

```
private class MyClass
{
    function void doit()
    {
        <<< "doing something" >>>;
    }
}

MyClass A;
<<< A, A >>>;
```

I get the following on the console:

> null 0x60400068ca80

**Comment by gewang** [comment]
Good catch.  Fixed, I hope.  Will be in 1.4.0.1.  Thank you!
