### ISSUE TITLE
adsr releaseTime is nan

### ISSUE THREAD

**Issue by lathertonj** [ccrma/chuck#144]
```
ADSR a;
a.set( 10::ms, 2::ms, 0.0, 10::ms );
<<< a.releaseTime() >>>;
```

-->
`nan :(dur)`

**Comment by mariobuoninfante** [comment]
ugen_stk.cpp

line 4999
```
MY_FLOAT ADSR :: getReleaseTime()
{ return sustainLevel / (releaseRate*Stk::sampleRate()); }
```

similar to https://github.com/ccrma/chuck/issues/116

**Comment by lathertonj** [comment]
Thanks for the reference! I think that this is then a big issue in how ADSR is written. We might call keyOff() before we even get to the sustain stage if the attack and decay are very long. It should release from whatever level it is at when we get to the keyOff, not always necessarily the sustain level.

@gewang is it a bad idea to change the source of how ADSR works at this point? I could always make an ADSR2 Chugin...

**Comment by mariobuoninfante** [comment]
@lathertonj, maybe I'm missing something obvious here, but shouldn't _releaseTime()_ just return the release time value regardless the current state of the ADSR?
as in, doesn't really matter if we're in the attack, decay, sustain or release phase, we're just interested in knowing the release value.
I suppose the same is true for attackTime(), decayTime() and sustainLevel().

**Comment by mariobuoninfante** [comment]
also because looking at the code and poking around with ADSR I think it releases properly regardless the state you're in when keyOff() is called

**Comment by mariobuoninfante** [comment]
I did a quick test on Linux and the following seems to fix this and #116 

in ugen_stk.h
from row 430 to 439 we should have

```
public:
  MY_FLOAT attackRate;
  MY_FLOAT decayRate;
  MY_FLOAT sustainLevel;
  MY_FLOAT releaseRate;
  // chuck
  MY_FLOAT m_attackTime;
  MY_FLOAT m_decayTime;
  MY_FLOAT m_releaseTime;
};
```

in ugen_stk.cpp at 4876 we should add
> m_attackTime = (MY_FLOAT) 0.;

then in _setAttackTime_ (row4957) we should have:
> m_attackTime = aTime;

then getAttackTime(), getDecayTime() and getReleaseTime() should return, respectively, m_attackTime, m_decayTime, m_releaseTime

I ran a quick test and it seems to work fine

**Comment by mariobuoninfante** [comment]
also, we should have setAttackRate(), setDecayRate() and setReleaseRate() updating m_attackTime, m_decayTime and m_releaseTime

ie 
> m_attackTime = attackRate * Stk::sampleRate();

**Comment by gewang** [comment]
Thank @mariobuoninfante for your work on this. We combed through ADSR to address the situations when sustain is either 1 or 0 and also made things hopefully more robust to various edge cases. The changes were pushed as of 20d717e and will be incorporated in 1.4.0.2. Please feel free to stress test this more.  Thank you!!
