### ISSUE TITLE
variable/scope issue

### ISSUE THREAD

**Issue by spencersalazar** [ccrma/chuck#16]
I encountered a strange case where a variable was changing value within the scope of an if statement, because I had a superclass with an identical variable name. I am able to reproduce it with this simple case:

```
class A 
{
    10000 => int foo;
}

class B extends A 
{
    fun void bar()
    {
        0 => int foo;

        <<< "a", foo >>>;
        {
            <<< "b", foo >>>;
        }
        <<< "c", foo >>>;
    }
}
```

Prints out:

```
a 0 
b 10000 
c 0 
```

(see https://lists.cs.princeton.edu/pipermail/chuck-users/2014-August/007688.html)

**Comment by gewang** [comment]
it's never too late to resolve an issue... pushed in cbe2c06
has to do with value lookup order when there is variable name shadowing...

FYI here is the latest value lookup precedence:
1) first look in the same scope
2) if not found, and if inside a class def, look up-scope within class (but no further)
3) if not found, and if inside a class def, look in parent (for inherited value)
4) if still not found, look all the way up to global scope
