### ISSUE TITLE
bugfix for chuck 1.4.0.1 for chout and fflush

### ISSUE THREAD

**Issue by BSWheeler42** [ccrma/chuck#161]
chuck 1.4.0.1 does not handle chout or fflush properly.
This impacts the Kadenze course Physics-Based Sound Synthesis for Games and Interactive Systems
assignment 1B: “PONG” with Physics and Sound Files

Add 2 lines to chuck_oo.cpp, and recompile.
In Chuck_IO_Chout::Chuck_IO_Chout( Chuck_Carrier * carrier ) {...
at 3112 add m_callback = NULL;
In Chuck_IO_Cherr::Chuck_IO_Cherr( Chuck_Carrier * carrier ) {...
at 3204 add m_callback = NULL;
In both classes, m_callback is tested against NULL later, without first being initialized.
I have recompiled chuck 1.4.0.1 and tested on my PC.

**Comment by gewang** [comment]
Thank you for this!  This has been fixed and merge into main (as part of PR #157) and will be included in 1.4.0.2.
