### ISSUE TITLE
ASIO build

### ISSUE THREAD

**Issue by spencersalazar** [ccrma/chuck#17]

**Comment by 3bst0r** [comment]
can I still build chuck with ASIO, as old forum posts suggest, and is there a tutorial that will likely work?

**Comment by lathertonj** [comment]
The part of ChucK that interfaces with the sound card is actually an external library called RtAudio. Looking at src/host/RtAudio, it seems you would want to disable the compilation flag `__WINDOWS_DS__ ` and enable `__WINDOWS_ASIO__` to try building for ASIO instead of DirectSound.

**Comment by gewang** [comment]
as of 1.5.0.0 ASIO support is now standard for Windows
