### ISSUE TITLE
OSC unit tests are flaky/segfault in silent mode on OSX mojave

### ISSUE THREAD

**Issue by nshaheed** [ccrma/chuck#210]
Running the unit test suite on a ccrma macbook fails - this is happening because running the osc test in silent mode sometimes causes a segfault:

```
> chuck --silent 03-Modules/osc03.ck 
"success" : (string)
Segmentation fault: 11
```

this doesn't seems to happen when running in real-time mode

Here's are the macbook specs:

OSX Version: 10.14.6 (18G103) [Mojave]
MacBook Pro (Retina, 15-inch, Late 2013)
Processor: 2.6 GHz Intel Core i7

**Comment by nshaheed** [comment]
this is happening on both 1.4.1.0 64-bit and HEAD 64 bit

**Comment by gewang** [comment]
i appear to be amidst a herd of OSC yaks...
cannot repro with 1.5.1.2 release on macOS Ventura (13.5) and OS X Sierra (10.12)
also tried the latest OSC update of 1.5.1.3

do we think this is still an issue?

**Comment by nshaheed** [comment]
I haven't really been developing with that computer much since then so I don't know if it's still happen, but imo if it's rare enough that we just haven't seen it since then I think we can close until it becomes a problem again

**Comment by gewang** [comment]
pr-lab ftw
