### ISSUE TITLE
termio.h is obsolete

### ISSUE THREAD

**Issue by barak** [ccrma/chuck#227]
There is logic to use either `termio.h` or `termios.h`, but (a) the case on architecture is done multiple times, both for the `#include` and later for the usage, and (b) according to **termio(7)**
```
The termio interface is now obsolete: POSIX.1-1990 standardized ... termios.
```
so `termios.h` should be used in preference to `termio.h` wherever possible.

This issue breaks building ChucK on a couple Debian architectures, namely Hurd and kfreebsd, where an attempt to include `termio.h` fails because it does not exist, but `termios.h` is available. See [build log]( https://buildd.debian.org/status/package.php?p=chuck ) for details.

**Comment by barak** [comment]
Pull request #228 addresses this issue.

**Comment by gewang** [comment]
Thank you barak -- PR #243 (including #228) is now merged into main
