### ISSUE TITLE
Enhancement: support c++17 on windows

### ISSUE THREAD

**Issue by dbadb** [ccrma/chuck#238]
Turns out chuck won't compile on windows with  the c++17 standard.  This is due to windows prior definition of 'byte' conflicting with std::byte introduced in c++17.  As a general "best-practice", `using namespace std` should only occur in .cpp and chuck has a few places where it's declared in a header.  Moving that out of header files is one part of the solution. The other is to ensure that windows.h (etc) must be included prior to a .cpp file's `using namespace std`.

[Here's](https://github.com/cannerycoders/chuck/commit/f661a26735c643ffab48a1680e8cd9e877e754c9) a changelist in the fiddle branch of my chuck repo.  I've verified that it works with c++17 on windows.

If there's interest, I can convert this into a clean PR off the main branch.

**Comment by gewang** [comment]
greeting @dbadb we recently made a pass with c++17 (working with ChucK and Unreal Engine 5 on windows); should now be c++17 compliant; please let us know if you run into any further issues. Thanks!

**Comment by gewang** [comment]
@nshaheed just verified 1.5 on windows c++17; closing issue for now; reopen if any new problems come up. Thank you!
