### ISSUE TITLE
chuck 1.4.2.0 build failure on x86 arch

### ISSUE THREAD

**Issue by chenrui333** [ccrma/chuck#240]
👋  trying to upgrade chuck to the latest release, but failed to build successfully on x86 arch

on macOS:
```
bash-3.2$ make -C src osx
-------------
[chuck-core]: compiling...
make osx -C core
[chuck-core]: all components built...
-------------
clang++ -o chuck  core/chuck.tab.o core/chuck.yy.o core/util_math.o core/util_network.o core/util_raw.o core/util_xforms.o host/RtAudio/RtAudio.o host/chuck_audio.o host/chuck_console.o host/chuck_main.o core/chuck.o core/chuck_absyn.o core/chuck_parse.o core/chuck_errmsg.o core/chuck_frame.o core/chuck_symbol.o core/chuck_table.o core/chuck_utils.o core/chuck_vm.o core/chuck_instr.o core/chuck_scan.o core/chuck_type.o core/chuck_emit.o core/chuck_compile.o core/chuck_dl.o core/chuck_oo.o core/chuck_lang.o core/chuck_ugen.o core/chuck_otf.o core/chuck_stats.o core/chuck_shell.o core/chuck_io.o core/chuck_carrier.o core/chuck_globals.o core/hidio_sdl.o core/midiio_rtmidi.o core/rtmidi.o core/ugen_osc.o core/ugen_filter.o core/ugen_stk.o core/ugen_xxx.o core/ulib_ai.o core/ulib_machine.o core/ulib_math.o core/ulib_std.o core/ulib_opsc.o core/ulib_regex.o core/util_buffers.o core/util_console.o core/util_string.o core/util_thread.o core/util_opsc.o core/util_serial.o core/util_hid.o core/uana_xform.o core/uana_extract.o core/lo/address.o core/lo/blob.o core/lo/bundle.o core/lo/message.o core/lo/method.o core/lo/pattern_match.o core/lo/send.o core/lo/server.o core/lo/server_thread.o core/lo/timetag.o core/util_sndfile.o  -isysroot /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -framework CoreAudio -framework CoreMIDI -framework CoreFoundation -framework IOKit -framework Carbon -framework AppKit -framework Foundation -F/System/Library/PrivateFrameworks -weak_framework MultitouchSupport -lc++ -lm
ld: warning: ignoring file core/chuck.tab.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64ld: warning: ignoring file core/chuck.yy.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64

ld: warning: ignoring file core/util_math.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file core/util_network.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file core/util_xforms.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file core/util_raw.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
ld: warning: ignoring file host/RtAudio/RtAudio.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
```

On linux

```
core/chuck.tab.o: file not recognized: file format not recognized
  collect2: error: ld returned 1 exit status
```

Any pointer would be appreciated. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/120230

**Comment by gewang** [comment]
Thank you for reporting this. I can't replicate this on my side but this issues looks like it's compiling on Intel MacOS (x86_64), but a number of files are trying to link against Apple Silicon object files (arm64). Are you compiling on an Intel machine? Which macOS version?

something to trying: 
a clean build using 'make mac' instead of 'make osx' (the latter is being phased out)
a clean build using 'make mac-ub' (this makes a universal binary)

I wonder if the makefile got confused in compiling certain source files (e.g., the ones in the host directory and/or .c files, guessing from the linker errors)

I'd love to help fix this issue. Please let me know how I might help. Thank you!

**Comment by p-linnane** [comment]
@gewang Hi 👋. @chenrui333 and I are Homebrew maintainers trying to package the latest release of chuck.

You can see the relevant GitHub Actions run here: https://github.com/Homebrew/homebrew-core/actions/runs/3897434188. All ARM64 versions of macOS build successfully, but all x86_64 versions (including Linux) failed. Please let us know how we can help here.

**Comment by gewang** [comment]
@p-linnane @chenrui333 thank you both very much for your work and for notifying us of this problem. I believe the issue has been located (it was entirely my mistake, having accidentally left binary .o files in the src/ and host/ directories—my sincere apologies). I have now updated the source tarball at https://chuck.cs.princeton.edu/release/files/chuck-1.4.2.0.tgz and the mirror at https://chuck.stanford.edu/release/files/chuck-1.4.2.0.tgz. If you would, could you verify this fixes the issue? Thank you!

**Comment by p-linnane** [comment]
Looks like that took care of it. I pushed the latest tarball and it built on all platforms. Thanks for your quick response on this!

**Comment by gewang** [comment]
That's a relief to hear! Thank you @p-linnane and @chenrui333.

**Comment by chenrui333** [comment]
Thanks @gewang!! Mystery solved. :)
