### ISSUE TITLE
Better scripting language

### ISSUE THREAD

**Issue by locriacyber** [ccrma/chuck#250]
After using ChucK a bit, I found that the built-in langauge is insufficient. For example, it doesn't have inline struct like `{x:0, y:1}`.

In theory, any language with cooperative scheduling can work. e.g. Lua (coroutine), Lisp (call/cc), Janet (fiber)

After looking through the code, I have no idea where to start.

**Comment by gewang** [comment]
Welcome! yeah guilty as charged, we need a better on-ramp for introducing people to chuck (and chuck development). There are computer music synthesis language with Lisp (Common Lisp Music), and probably with Lua and Janet, too. Also, is there a specific issue you'd like to contribute?

**Comment by locriacyber** [comment]
The problem now is: the audio engine of ChucK is solid and well designed, but the scripting language is not. For example, no inline object literal (object constructor).

I think it would be better to use a general purpose programming language for scripting, or provide API for C/C++/Rust.

I'd like to add such a language to chuck. If possible, I'd like to separate the scripting language (VM,parser,etc) away from `core`.

**Comment by gewang** [comment]
A lot of people, myself included, have worked hard on ChucK for many years (audio engine and language and much more), and as imperfect as these may be, please be sensitive when stating your opinions like "this is well designed, that is not well designed". The scripting language component is always in development (and quite unfinished) and yes you make a good point that it could have a lot more quality-of-life improvements (including object constructors, better array initialization, string handling, etc). To be honest, as the chief designer of the language, I am satisfied with **neither** the audio engine or the language as they stand, but I am interested deeply in making these better, with the belief that different tools/languages have different things to offer how we work, how we think, and perhaps even how we feel. Not everything has to boiled down to the few widely used languages of the day (as nice as these may be), nor is getting another language to behave like ChucK as straightforward as you might think. If you are interested in improving the language as a whole, and not just gutting it for the parts you find useful, you are welcome to submit ideas or pull requests to add specific language features that you'd like to see and use.

**Comment by locriacyber** [comment]
> please be sensitive when stating your opinions like "this is well designed, that is not well designed".
Sorry for my criticism.

> Not everything has to boiled down to the few widely used languages of the day (as nice as these may be)
I've used 60+ different languages so far, and has also designed my own. I think Lua is a good existing choice out of all the languages I've tried.

> nor is getting another language to behave like ChucK as straightforward as you might think
Integrating with existing codebase is hard. Making Lua code run as shred is straight forward.

> If you are interested in improving the language as a whole, and not just gutting it for the parts you find useful, you are welcome to submit ideas or pull requests to add specific language features that you'd like to see and use.
I'm interested in the audio engine, not the language.

**Comment by gewang** [comment]
There has been a healthy and welcome history of ChucK and ChucK-esque "strongly-timed" being ported to other languages, including Python (https://github.com/zputin/pyChuck, although not a deep integration). It would be interesting to see ChucK integrated into Lua and other languages.

**Comment by znmeb** [comment]
> There has been a healthy and welcome history of ChucK and ChucK-esque "strongly-timed" being ported to other languages, including Python (https://github.com/zputin/pyChuck, although not a deep integration). It would be interesting to see ChucK integrated into Lua and other languages.

I'm attempting to build something with ChucK-style strongly-timed audio for micro-controllers in Forth. Is there some kind of "under-the-hood" description of how the audio in ChucK is done? I'm assuming raw micro-controller audio, no libraries like ALSA / JACK / Pulseaudio, etc.

**Comment by locriacyber** [comment]
> > There has been a healthy and welcome history of ChucK and ChucK-esque "strongly-timed" being ported to other languages, including Python (https://github.com/zputin/pyChuck, although not a deep integration). It would be interesting to see ChucK integrated into Lua and other languages.
> 
> I'm attempting to build something with ChucK-style strongly-timed audio for micro-controllers in Forth. Is there some kind of "under-the-hood" description of how the audio in ChucK is done? I'm assuming raw micro-controller audio, no libraries like ALSA / JACK / Pulseaudio, etc. The Forth I'm using has complete real-time operating system functionality.

Maybe you can try porting https://github.com/WickedSmoke/sfx_gen to microcontroller.

**Comment by znmeb** [comment]
> Maybe you can try porting https://github.com/WickedSmoke/sfx_gen to microcontroller. It's a C library. Not sure if you can make it to work with Forth.

I'm more interested in how the "ChucK virtual machine" works - shreds, sporks, internal communication mechanisms, how it goes from me ChucKing something to `now` to sending the samples to a library. I have everything I need to send samples to a DAC (either one at a time or buffered) and to generate the samples from unit generators.

**Comment by locriacyber** [comment]
I'm not sure about the actual implementation.

When `xxx => now`, the shred is paused until that time. If all shreds are paused, time advance until any shred need to be waken.

The event loop is similar to Node.js's event loop with "ticks".

For pausing, I find `coroutine.yield` in Lua similar.
