### ISSUE TITLE
add bounds to filters to prevent blowing up

### ISSUE THREAD

**Issue by nshaheed** [ccrma/chuck#256]

**Comment by gewang** [comment]
looking into this long time issue; I have been able to repro the filter blow up for LPF and HPF for low values of freq (<.15); have not been able to replicate blow up with BPF and BRF so far (anyone here remember experiencing BPF and BRF filter explosions?)

**Comment by gewang** [comment]
a potential fix pushed in d53cdfb, with accompanying test in 8276afc; will leave this issue open for now for any additional verification

**Comment by nshaheed** [comment]
fwiw the SC ugen this is based off of (https://doc.sccode.org/Classes/LPF.html) also warns about setting low cutoff frequencies, so any improvements to this are an improvement from the baseline

**Comment by DBraun** [comment]
Make sure to watch out for frequency cutoffs that are too high that could cause a blowup.

**Comment by gewang** [comment]
thanks @DBraun -- indeed upon further testing, LPF/HPF tends to blow up as the cutoff frequency get beyond Nyquist--or _below_ the Nyquist frequency if Q is less than 1. Clamping the cutoff to the Nyquist seems sensible; are there practical cases where we would want Q less than 1? If not, we would also clamp Q to be >= 1.

**Comment by gewang** [comment]
pushed 190223f with above proposed clamps (.freq within [1,nyquist] and .Q no less than 1; btw already Q is implicitly clamped to no greater than 1000), as well as test 125.ck for high cutoff frequencies

**Comment by gewang** [comment]
considering this issue closed @nshaheed @celestebetancur @gewang
