### ISSUE TITLE
bluetooth headphone fix

### ISSUE THREAD

**Issue by nshaheed** [ccrma/chuck#257]
issue with sample rate interpolation not existing

**Comment by gewang** [comment]
this issue has been addressed as part of a larger audio system update 65004c1f5ded8648ab15d3cac52b87f01683e9be 65004c1f5ded8648ab15d3cac52b87f01683e9be 7ff8ccfc1f23e72ebb89c5e5df585119ad21193a will be released as part of chuck-1.5.0.0
