### ISSUE TITLE
Question about 'dyno' UGEN

### ISSUE THREAD

**Issue by dfkettle** [ccrma/chuck#26]
I don't know if this is a bug or just a lack of understanding on my part, but I was experimenting with the 'dyno' UGEN and saw some results which don't make sense to me. I ran the code below from miniAudicle:

adc => Gain g => Dyno dyno => dac;
dyno.limit();
5::ms => dyno.attackTime;
300::ms => dyno.releaseTime;
<<< "slopeAbove =", dyno.slopeAbove() >>>;
<<< "slopeBelow =", dyno.slopeBelow() >>>;
<<< "thresh =", dyno.thresh() >>>;
<<< "attackTime =", dyno.attackTime() >>>;
<<< "releaseTime =", dyno.releaseTime() >>>;
<<< "externalSideInput =", dyno.externalSideInput() >>>;

And this was displayed in the console:

slopeAbove = 0.100000 
slopeBelow = 1.000000 
thresh = 0.500000 
attackTime = 13230.000000 
releaseTime = 13230.000000 
externalSideInput = 0 

After scratching my head a bit, I figured out that the attackTime and releaseTime are printed as number of samples (assuming a 44100 sample rate), but shouldn't the attackTime be 220.5 (possibly rounded or truncated to an integer)?

I'm running version 1.3.5.0-beta-7 (Windows 32-bit), which I believe is the latest version for Windows. Also, in general, I've noticed that the default values for UGEN's aren't always as stated in the documentation.

Thanks.

**Comment by dfkettle** [comment]
P.S. I changed the order of the two assignment statements and now both parameters are getting set to 220.5:

300::ms => dyno.releaseTime;
5::ms => dyno.attackTime;

In console:

attackTime = 220.500000 
releaseTime = 220.500000 

So it looks like both are getting set whenever you chuck something to either one, which I assume isn't the correct behaviour.

**Comment by spencersalazar** [comment]
Hello,

That definitely seems off- I will have a look at the source code and see what could be going wrong. Probably an easy fix. Thanks for letting us know! 

spencer

**Comment by spencersalazar** [comment]
Fixed in 15b5b0d804403248bd8c80bdc58e5138a42ec1b2 !
