### ISSUE TITLE
make install error in linux

### ISSUE THREAD

**Issue by dsoum** [ccrma/chuck#266]
when I try ```sudo make install``` I got this error.
```bash
profshonku@Uranus:~/Downloads/chuck-1.4.2.0/src$ sudo make install
mkdir -p /usr/local/bin
cp  /usr/local/bin/
cp: missing destination file operand after '/usr/local/bin/'
Try 'cp --help' for more information.
make: *** [makefile:18: install] Error 1

```

**Comment by nshaheed** [comment]
did you call `make linux-{alsa,pulse,jack}` to build chuck before calling `make install`? It looks like it isn't finding the chuck binary

**Comment by dsoum** [comment]
Actually there was a problem on calling ```make linux-alsa``` as desribed at https://github.com/ccrma/chuck/issues/265

**Comment by dsoum** [comment]
ok! its working now. (after successfully calling make ```linux-alsa```.
