### ISSUE TITLE
unpredictable crackling audio with LiSa loops

### ISSUE THREAD

**Issue by szymonkaliski** [ccrma/chuck#27]
I've build simple looper on Raspberry Pi → https://github.com/szymonkaliski/LoopPI — I'm using latest archlinux, jack, and chuck. My looper code is here: https://github.com/szymonkaliski/LoopPI/blob/master/Looper/looper-class.ck

Unfortunately I have very hard to debug / catch problem — after some time (differs every time I test it, sometimes 5 minutes, sometimes 3 hours) new recordings produce crackling sound, what is strange if I have 4 loops, three of them are playing (looping) fine, just when I'm recording to fourth one after some time it begins to crackle. I couldn't find correlation between this and any jack/chuck settings (I've played with buffer sizes, niceness, jack priorities, etc). I also couldn't find any correlation with system settings (swap on/off, with and without overclocking), or the app itself (two or four loops — it seems not to be happening with one loop, or maybe I was just lucky / didn't wait long enough)... I even installed fresh system on new SD card and set it up from grounds up, it didn't help. I'm completely lost.

I'm almost 100% sure it's something with chuck, because if the jackd/linux/hardware was a problem then all loops would start to crackle, but they don't, just the "new" one.

Any help / pointers / direction would be greatly appreciated. I slowly start to think that I should just give up and try re-writing this in some other language, that would be a shame though, as ChucK is fun to play with :)

**Comment by spencersalazar** [comment]
Hi Szymon,

Sorry to hear you are having these difficulties. Sounds like a cool app. To make an educated guess, I would say the crackling is coming from creating a new LiSa and setting it to 8 seconds of record time. Theoretically that should be harmless enough, but, under the hood, this causes ChucK to allocate a little over 1MB of memory, which (in my experience) is large enough to cause audio hiccuping if done while audio is currently processing. 

Ideally ChucK would automatically split up that allocation so it doesn't cause any glitches. But given that thats not the case right now, is it possible to create all of your LiSa objects right when your program starts? If there is an easy/straightforward way to try/test that, it could reduce problems with audio glitching. 

spencer

**Comment by szymonkaliski** [comment]
Hi Spencer,

yes, I'm allocating all loops at the start of the app, so there's no re-creating when I hit record, all four are looping all the time, I just clear them or mute them if I don't need them.

I've been doing a lot more tests and I also connected audio input to output using jack routing, and when the cracks appear the sounds is also crackling with jack only (with all the loops with volumes set to 0), so I think the problem might be elsewhere after all... It strangely appears after some time of input inactivity, so I'm starting to think this might be some power saving (?) related thing, but I need to investigate more, the worse thing is, sometimes it takes few hours to get the crackling sound, so feedback loop between changes and output is very long...

Well, if you have any input / pointers that would be great :) otherwise I'm closing the thread, as it's probably not chuck-related after all, sorry for that.

**Comment by spencersalazar** [comment]
Urgh, thats unfortunate. I would try ALSA if possible (make linux-alsa when you build chuck) and maybe also try to disable PulseAudio if that is installed/enabled. 

Also what device are you using for audio input? At least on some of the older models of RPi using a powered USB hub made USB stuff work better in general, so maybe that is still the case, if you are using a USB audio interface for input.

**Comment by szymonkaliski** [comment]
Thanks for all your help! I'll compile ChucK and check, yeah, I was thinking about power too, but then the output from other loops would be cracking as well, the thing is — only output that's rooted from microphone cracks when this happens. So I think the problem is software-related...

Thanks again!
