### ISSUE TITLE
WvOut MAT-file  crash

### ISSUE THREAD

**Issue by cchafe** [ccrma/chuck#273]
when closing mat file output, an assert is thrown at ugen_stk.cpp:18976

` return ::fclose(stream);`

happens 100% of the time

> chuck version: 1.4.1.0 (numchucks)
   linux (jack) : 64-bit

test with 
[WvOut.matBug.ck.txt](https://github.com/ccrma/chuck/files/11226666/WvOut.matBug.ck.txt)

**Comment by gewang** [comment]
This issue has been addressed in 45aeaf156033bf34f32884e47e961d0afc3a33d6 and will be part of the upcoming chuck-1.5 release;  also addressed in same commit: WvIn/WaveLoop playback now correctly normalizes non-16bit data formats (previously was normalizing as if 16bit signed int, regardless of format).

Thanks @cchafe! please let us know if you run into any further issues!
