### ISSUE TITLE
ChucK Installer Interface Inconsistencies

### ISSUE THREAD

**Issue by terryzfeng** [ccrma/chuck#285]
<img width="622" alt="image" src="https://user-images.githubusercontent.com/50178575/236052038-36bed643-c2d6-445a-b4cd-2941d25762a4.png">

version 1.5.0-rc1

ChucK Logo is covered 

Also needs to be updated to the new logo

14" MBP

**Comment by gewang** [comment]
updated (see both light and dark mode) as of 1.5.0.2

<img width="732" alt="Screenshot 2023-06-18 at 2 31 18 AM" src="https://github.com/ccrma/chuck/assets/669967/39bad974-ca26-416a-84fd-4ca1eee0923c">
<img width="732" alt="Screenshot 2023-06-18 at 2 33 08 AM" src="https://github.com/ccrma/chuck/assets/669967/81215fa8-6c58-4ca6-a969-50f2092becd6">
