### ISSUE TITLE
Lookup audio devices by name

### ISSUE THREAD

**Issue by nshaheed** [ccrma/chuck#324]
support --adc and --dac to allow for looking up audio devices by name (i.e. a string) and not just index.

**Comment by ynohtna** [comment]
I think this can be closed.

Specifying --adc and --dac with partial names (i.e. "Speak" and "Mic" on a MacBook Pro) works out of the box on recent Chuck builds.

**Comment by gewang** [comment]
interesting, this feature seem to have existed since 2012...
https://github.com/ccrma/chuck/blame/main/VERSIONS#L2673-L2682
