### ISSUE TITLE
trailing single-line comment causes a crash

### ISSUE THREAD

**Issue by gewang** [ccrma/chuck#366]
```
<<< 1 >>>; // 
```

**Comment by cchafe** [comment]
Not here.  (quick test inserting this in a rather complex .ck file)
Running chuck version: 1.5.0.4 (chai)

**Comment by nshaheed** [comment]
chris, are you running on linux? I just tried ge's example from HEAD on ubuntu and it didn't crash either

**Comment by cchafe** [comment]
fedora 38

**Comment by nshaheed** [comment]
Just tried HEAD on windows and it works fine, seems like it's a mac-only error?

**Comment by gewang** [comment]
for me it crashes miniAudicle (macOS) but not CLI chuck on the same computer...

**Comment by gewang** [comment]
more info: it seems to crash consistently for me on linux and mac, miniAudicle and CLI chuck if the code is not read from file, but compiled from a string, e.g., run from `Machine.eval()`
```
// this seems to crash more reliably
Machine.eval( "<<< 1 >>>; // " );
```
