### ISSUE TITLE
comments causing crash (or not being formatted as comments unless followed by an empty line)

### ISSUE THREAD

**Issue by mhzareei** [ccrma/chuck#369]
Hello again,
When trying to run some older codes on miniAudicle I started getting crashes and realised that it was due to the commented text not being formatted as such unless an empty line is added after:

<img width="374" alt="Screenshot 2023-09-19 at 9 49 41 AM" src="https://github.com/ccrma/chuck/assets/32470353/4f6fbf80-e38f-4a2c-8b42-141a3d83a91b">

Adding the shred above would give me this error:
[comment error.txt](https://github.com/ccrma/chuck/files/12653766/comment.error.txt)

Adding a line would fix the colour coding of the comment and in turn the crashing issue.

<img width="361" alt="Screenshot 2023-09-19 at 9 49 48 AM" src="https://github.com/ccrma/chuck/assets/32470353/26aa079a-5b48-4568-8fa5-b403e3d0037e">

**Comment by gewang** [comment]
thanks for the report!
FYI the above code will crash miniAudicle but not CLI chuck, unless you try to eval it from string `Machine.eval("//comment");`

this appears related to #366, and a fix has been pushed in bd4dc38; the fix will be part of chuck-1.5.1.4

**Comment by mhzareei** [comment]
Great thanks!
