### ISSUE TITLE
`popFront()` doesn't work with objects

### ISSUE THREAD

**Issue by terryzfeng** [ccrma/chuck#420]
Code to reproduce:
```js
class Msg {
    int val;
}

Msg a; 1 => a.val;
Msg b; 2 => b.val;

Msg msg[0];
msg << a << b;
msg.popFront();
```

Kills miniAudicle and also dies when running on WebChucK (1.5.1.6). I was able to get popFront working with ints, but it doesn't seem to work with object arrays.

**Comment by gewang** [comment]
ooooops good catch
fixed in 6718dbf; will be part of 1.5.2.0
