### ISSUE TITLE
Array constructors for ugens only affects first element of array

### ISSUE THREAD

**Issue by nshaheed** [ccrma/chuck#425]
```
Step s(2)[2] => blackhole;

while(100::ms => now) {
    <<<s[0].last(), s[1].last()>>>;
}
```

This outputs

```
2.000000 0.000000
2.000000 0.000000
2.000000 0.000000
2.000000 0.000000
2.000000 0.000000
2.000000 0.000000
2.000000 0.000000
```

afaik both of these values should be 2

**Comment by gewang** [comment]
after testing, the array constructors seem to be working properly; this appears to be a behavior (possible bug) with `=>` between arrays. more investigation underway...

**Comment by gewang** [comment]
semantics for => connecting arrays of UGens have been updated in d070fa8fffaaf59f19ad6b2dcaf66c17e62a6aae
