### ISSUE TITLE
Crash for comma in array subscript

### ISSUE THREAD

**Issue by spencersalazar** [ccrma/chuck#43]
The following code causes ChucK to crash during compilation:

```
[[53,57,60,63],[57,60,63,69]] @=> int chordz[][];
54 => chordz[0,0];
```

The issue seems to be the comma in the array subscript, which is not valid syntax, but should generate a compile error rather than crashing.

**Comment by tim-torres** [comment]
Hey Spencer,

The crash stems from a failure of the following assertion in the `type_engine_check_exp_array` function of `chuck_type.cpp` 
>        assert( array->indices->depth == depth );
As you requested, I rephrased the assertion as an error.
>     if( array->indices->depth != depth)
>     {
>       EM_error2( array->linepos,
>           "int[..., ...] is invalid syntax.");
>       return NULL;
>     }

I'll be the first to admit it's an ugly patch. I tried following the erroneous value (`depth`) upstream--It's dictated by the number of elements in `exp_list`, which itself is set exclusively by generated code, so I don't think much else can be done.

>        int z[5, 3, 2, 4, x];
I also discovered that the above code successfully compiles, producing a length _x_ int array of zeroes...How tedious would it be to disallow commas inside hard brackets on the right side of the ChucK operator?

**Comment by spencersalazar** [comment]
Hey Tim,

Cool, thats a good analysis. I think the most general solution would be to disallow comma expressions in array subscripts (e.g., right after a variable name) while continuing to allow them in array literals, though Im not sure off the top of my head where that distinction is made in the parser/compiler system. Ideally it could be caught in the .y file which defines ChucK's grammar. Your proposed patch seems like a good solution to start with; if you want to make a pull request with that change, that'd be great! 

spencer

**Comment by tim-torres** [comment]
Christ, this looks like a warzone... Was just trying to change my branch's name--What a mess!
