### ISSUE TITLE
add wildcard support for OSC addresses

### ISSUE THREAD

**Issue by gewang** [ccrma/chuck#432]
look into liblo within chuck; may already support wildcard

**Comment by nshaheed** [comment]
https://github.com/radarsat1/liblo/blob/master/examples/example_client.c#L53-L59

Looks like it does have wildcard support with the current version

**Comment by nshaheed** [comment]
https://github.com/ccrma/chuck/blob/7e30200af906b3e8608095f570ef7ca07731f2d6/src/core/lo/server.c#L1033

Seems like chuck's version does have support, maybe the error message we're seeing is just erroneously stopping wildcards from being passed through and we can just remove the check

**Comment by gewang** [comment]
https://github.com/ccrma/chuck/blob/7e30200af906b3e8608095f570ef7ca07731f2d6/src/core/lo/server.c#L1235-L1237

removing the check in `lo_server_add_method()` gets rid of the error message, but it does appear to receive messages; I wonder if there is something else at play

I did create a [new branch](https://github.com/ccrma/chuck/tree/2024-osc-wild) with the latest liblo release (0.32), and duct-taped it into place, and wildcards now work (at least on macOS), but I am not confident if things might be amiss in general, since I used the old `config.h` and `lo_endian.h` to get things to compile
