### ISSUE TITLE
auto on multi-dimension array fails in for loop

### ISSUE THREAD

**Issue by nshaheed** [ccrma/chuck#441]
The following code:

```
[[ 1, 2], [3, 4, 5], [6], [7, 8]] @=> int grid[][];


for (auto arr: grid) {
    for (auto val: arr) {
        <<< val >>>;
    }
}
```
[(webchuck link)](https://chuck.stanford.edu/ide/?code=%5B%5B+1%2C+2%5D%2C+%5B3%2C+4%2C+5%5D%2C+%5B6%5D%2C+%5B7%2C+8%5D%5D+%40%3D%3E+int+grid%5B%5D%5B%5D%3B%0D%0A%0D%0A%0D%0Afor+%28auto+arr%3A+grid%29+%7B%0D%0A++++for+%28auto+val%3A+arr%29+%7B%0D%0A++++++++%3C%3C%3C+val+%3E%3E%3E%3B%0D%0A++++%7D%0D%0A%7D)
Gives the compiler error

```
untitled:4:6: error: for( X : ARRAY ) X [int] must have one less array dimension than ARRAY [int[][]]
[4] for (auto arr: grid) {
```

However, if I explicitly set the type it works:

```
[[ 1, 2], [3, 4, 5], [6], [7, 8]] @=> int grid[][];


for (int arr[]: grid) {
    for (auto val: arr) {
        <<< val >>>;
    }
}
```

**Comment by gewang** [comment]
fixed in 9c3ee54083911ff0d293d4ab058828e5f39b8123; will be part of 1.5.4.4
