### ISSUE TITLE
CKDoc add option to disable alphabetical sorting 

### ISSUE THREAD

**Issue by AndrewAday** [ccrma/chuck#444]
CKDoc always sorts the member functions documentation of a class alphabetically.
This is disadvantageous for large classes with many variables / functions that are better grouped semantically.

Option could look like: 

```c
CKDoc doc;
doc.sortAlphaNumeric(false);
```

**Comment by gewang** [comment]
PR merged 15e334392005e5f43453eaeaeb92cfbfcc8248ed

```c
CKDoc doc;
doc.sort( false );
```
