### ISSUE TITLE
CKDoc Link in GenX is broken

### ISSUE THREAD

**Issue by terryzfeng** [ccrma/chuck#453]
Documentation linked in GenX is broken. 

https://chuck.stanford.edu/doc/reference/ugens-advanced.html#GenX

**Comment by gewang** [comment]
good catch! looks like that page has moved on; for now using the most recent WayBack page I can find: 
https://web.archive.org/web/20160628032324/http://www.music.columbia.edu/cmix/makegens.html

(let me know if you find a better URL to link to) thanks!

**Comment by terryzfeng** [comment]
Thanks for updating this! I'll update the IDE side accordingly :D
