### ISSUE TITLE
for loop resolution for floating point iterator issue

### ISSUE THREAD

**Issue by mhzareei** [ccrma/chuck#456]
Hi team,
A student just bring this to my attention. In the following code, with increments of 0.01, the if statement doesn't seem to be reached somehow

```
0 => float state; 

for (0.0 => float f; f < 1.0; f+0.01 => f){
    
    if (f == 0.50){
        <<<"reaching me?">>>;
        -1 => state;
    }

    10::ms => now;   
}
<<<state>>>;
```
I get nothing printed and the value of state remains zero.

But by modifying the for loop resolution to increments of 0.1, things work as expected:

```
0 => float state; 

for (0.0 => float f; f < 1.0; f+0.1 => f){
    
    if (f == 0.50){
        <<<"reaching me?">>>;
        -1 => state;
    }

    10::ms => now;   
}
<<<state>>>;
```

To get around this, the following code does report the result, but with only one printed line (instead of the expected 10 lines):

```
0 => float state; 

for (0.0 => float f; f < 1.0; f+0.01 => f){
    
    if (f > 0.49 && f < 0.5){
        <<<"reaching me?">>>;
        -1 => state;
    }
    
    10::ms => now;   
}
<<<state>>>;
```

And lastly, this one seems to be working too:

```
0 => float state; 

for (0.0 => float f; f < 1.0; f+0.01 => f){
    
    if (f > 0.490 && f < 0.491){
        <<<"reaching me?">>>;
        -1 => state;
    }
    
    10::ms => now;   
}
<<<state>>>;
```
I've tried this on WebChucK too so it won't be a miniAudicle problem. But yeah, very confusing... 
Any clarification or help would be appreciated.

Best,
Mo

**Comment by DBraun** [comment]
I think this issue is related to the nature of floating point numbers, and the same behavior can be observed in other languages. For example, check out the Python docs for some of their edge cases https://docs.python.org/3/tutorial/floatingpoint.html

Maybe having a utility function for fun float isClose(float x, float y) { return abs(x-y)<.0001;} could help? Or redesign your for loop to use integers which shouldn’t have this issue.

**Comment by mhzareei** [comment]
Thanks for your quick reply David. Very helpful. That makes total sense! 

This is a 1st year digital music class and a student came across this issue, and we've just started for loops (no functions yet).
But the examples on the Python docs make it super clear. So thanks again for that!

**Comment by nshaheed** [comment]
David is correct, just wanting to add that chuck does provide this utility function already in `Math`:

```
Math.equals(1.0, 1.00000000001) // Returns true because the different between the two numbers is very small
```
