### ISSUE TITLE
miniAudicle crashes when an integer is divided by zero

### ISSUE THREAD

**Issue by vladimir-kazakov** [ccrma/chuck#46]
The following line of code reproduces the issue:

```
<<< 2 / 0 >>>;
```

miniAudicle: 1.3.5.2 (the About dialog says: 1.3.5.2-beta-3 (chimera) 32-bit).
OS: Windows 10 Pro, 64-bit.

**Comment by spencersalazar** [comment]
Thanks Vladimir! We will look in to this further.

**Comment by Arseniusz** [comment]
MiniAudicle crashes on Debian8 with same case.

**Comment by jack461** [comment]
The  <<< 2 / 0 >>>; bug is still there.
Using miniAudicle version 1.3.5.2 (gidora)  git: a8d59b9 on a Mac...

**Comment by lathertonj** [comment]
This was fixed in 7d8e54a861bfe84d1637177d3a1b1cf46182b36f, which is in master and will be in miniAudicle the next time a new version of ChucK is associated with the miniAudicle build. For now, I think that building ChucK / miniAudicle yourself should eliminate this behavior.

**Comment by markcerqueira** [comment]
Checks 7d8e54a and sees unit tests were added. 😭 (tears of joy) Thanks @lathertonj!

Given this bug was opened over a year ago, are there any plans to get this fix out publicly?

**Comment by spencersalazar** [comment]
Im down to put together a release (and work towards documenting + generalizing the release process so anyone else or CI can build releases) within the next month or so.

**Comment by gewang** [comment]
combing through open tickets... thanks @vladimir-kazakov @spencersalazar @Arseniusz @jack461 @lathertonj and @markcerqueira

resolution verified in latest miniAudicle (1.5.1.2)
```
[chuck](VM): DivideByZeroException: on line[1] in shred[id=1:Untitled]
```
