### ISSUE TITLE
Virtual Machine cannot be stopped

### ISSUE THREAD

**Issue by vladimir-kazakov** [ccrma/chuck#47]
When I click the "Start Virtual Machine" button in the Virtual Machine window, in miniAudicle, the button changes its text to "Stop Virtual Machine" and becomes disabled (grayed out). So, there's no way to stop the virtual machine without restarting miniAudicle.

miniAudicle: 1.3.5.2 (the About dialog says: 1.3.5.2-beta-3 (chimera) 32-bit).
OS: Windows 10 Pro, 64-bit.

**Comment by spencersalazar** [comment]
Thanks Vladimir- this is a somewhat challenging issue as the audio library we use does not seem to allow stopping without closing the app entirely. We have been investigating alternatives but it will be somewhat time-consuming to change to a different library.

**Comment by gewang** [comment]
this issue has been resolved as of 1.5.0.0; it was part of the upgrade from Qt4 to Qt6 by @spencersalazar

**Comment by gewang** [comment]
if you'd like, come hang in the [ChucK Community Discord Server](https://discord.gg/ENr3nurrx8);
check out the latest in ChucK offerings => https://chuck.stanford.edu/
