### ISSUE TITLE
me.dir() return empty string if programm add with command line.

### ISSUE THREAD

**Issue by Arseniusz** [ccrma/chuck#48]
Linux version 3.16.0-4-amd64
Debian GNU/Linux stretch
gcc version 4.8.4

`me.dir() => string root;

<<< root >>>;

Machine.add(root + "Utils.ck");
Machine.add(root + "Sampler.ck");
Machine.add(root + "BPM.ck");
Machine.add(root + "Mixer.ck");`

When I add to vm chuck program with miniAudicle <<< root >>>; print to console right path, but if I trying to **start chuck with 'chuck --loop' from my home directory** and then adding script with 'chuck + myProgramm.ck' i have got an error:

[chuck](VM): sporking incoming shred: 1 (import.ck)...
"" : (string)
[Utils.ck]: no such file or directory
[Sampler.ck]: no such file or directory
[BPM.ck]: no such file or directory
[Mixer.ck]: no such file or directory

if I start chuck from same directory with myProgramm.ck <<< root >>> print correct path.

**Comment by gewang** [comment]
on a mission to (slowly) clean up time-honored issues... verify (1.5.1.3) this no longer seem to be an issue; considering this issue closed. If problems persist, please feel free to re-open. Thank you for reporting!

**Comment by gewang** [comment]
if you'd like, come hang in the [ChucK Community Discord Server](https://discord.gg/ENr3nurrx8);
check out the latest in ChucK offerings => https://chuck.stanford.edu/
