### ISSUE TITLE
Crash when trying to use a Chugen

### ISSUE THREAD

**Issue by ivant** [ccrma/chuck#52]
```
class Crash extends Chugen {
  fun float tick(float v) {
    return v;
  }
}

SinOsc s => Crash c => dac;
440.0 => s.freq;
1::second => now;
```

Crashes in `Chuck_VM_Shred::run` due to `vm_ref` being `0x0`. Replacing `vm_ref` with `vm` fixes the crash, but it's unclear to me if that's a correct thing to do.

**Comment by spencersalazar** [comment]
Fixed as of 8407e3ef2d6385eb507befb754b612c60ca3c749. Thanks for bringing this to our attention!
