### ISSUE TITLE
OSC messages from a python-osc client are not picked up by ChucK server

### ISSUE THREAD

**Issue by Chiel92** [ccrma/chuck#54]
I'm trying to set up OSC communication between chuck and python-osc. It appears that the messages we send from the python side do not arrive at the chuck side. All other combinations, i.e. python to python, chuck to chuck and chuck to python are working fine though.
I'm running python 3.4.4 on windows 7.
What could be going wrong here?

Here are the four files with the client/server implementations I'm using for testing.

### chuck_client.py:

    OscSend xmit;
    xmit.setHost("localhost", 5005);
    <<<"Sending">>>;
    xmit.startMsg("/debug");

### chuck_server.py:

    OscRecv orec;
    5005 => orec.port;
    orec.listen();
    orec.event("/debug") @=> OscEvent e;
    
    <<<"Waiting">>>;
    e => now;
    <<<"Received">>>;

### python_client.py:

    from pythonosc import osc_message_builder
    from pythonosc import udp_client
    
    client = udp_client.UDPClient('localhost', 5005)
    msg = osc_message_builder.OscMessageBuilder(address="/debug")
    msg = msg.build()
    print('Sending')
    client.send(msg)

### python_server.py:

    from pythonosc import dispatcher
    from pythonosc import osc_server
    
    dispatcher = dispatcher.Dispatcher()
    dispatcher.map("/debug", lambda _: print('Received'))
    
    print('Waiting')
    server = osc_server.ThreadingOSCUDPServer(
        ('localhost', 5005), dispatcher)
    print("Serving on {}".format(server.server_address))
    server.serve_forever()

**Comment by markcerqueira** [comment]
@Chiel92 - you may have better luck asking this question on the [chuck-users mailing list][1] as well since you'll get more reach (i.e. contact more chuck users) there.

[1]: https://lists.cs.princeton.edu/mailman/listinfo/chuck-users

**Comment by spencersalazar** [comment]
This might be a problem with python-osc. Tested python_client.py above with OSC servers in ChucK, Processing, and oscdump, and none of them successfully receive a message. 

oscdump reports this error after sending the message from the Python client:

```
$ oscdump 5005
liblo server error 9902 in path /debug: Invalid message received
```

**Comment by hg42** [comment]
[without any knowledge about pythonosc or test]

from this page
python-osc 1.5 : Python Package Index
https://pypi.python.org/pypi/python-osc

---snip---
  for x in range(10):
    msg = osc_message_builder.OscMessageBuilder(address = "/filter")
    msg.add_arg(random.random())
    msg = msg.build()
    client.send(msg)
    time.sleep(1)
---snap---

Just a quick guess: message sending may be asynchronous, so the client would be terminated before the message is completely sent. That's not a real scenario, usually the client would run for some time while sending messages here and there.

May be you have to wait for a queue length or something like that before exiting.

For a test, you could try adding a time.sleep(10) for example to be sure the message transfer has really finished.

Another difference in the code is the additional use of add_arg, perhaps an argument is mandatory?
But I think, that's not very likely.

**Comment by Chiel92** [comment]
Appeared to be a bug in python-osc 1.5. Version 1.6 fixes this.
