### ISSUE TITLE
Method to inspect VM status

### ISSUE THREAD

**Issue by hughrawlinson** [ccrma/chuck#66]
I'm trying to write a ChucK shred that detects when all but two (itself and a `rec.ck`) shreds have finished in the VM. I realise the `Machine.status` method prints the status of the VM, but it returns an integer (I keep getting `-16`), and I can't quite figure out what the integer represents. I haven't found any documentation on what the return value of this function represents, and I've looked through the source code, but I haven't quite understood how calls to the standard libraries are handled in the VM.

Is it currently possible to determine how many shreds are running in the VM from code? If not, would you be open to a PR for this functionality in the `Machine` lib?

**Comment by spencersalazar** [comment]
Hi Hugh,

Im not sure what `Machine.status` is supposed to return. `Machine.shreds()` should do what you are looking for- this returns an array of shred ids that are currently active. See https://ccrma.stanford.edu/~spencer/ckdoc/stdlib.html#Machine for more info. (Tangentially I would be very open to a PR that fills in the Machine ckdocs or any other currently missing areas!)

**Comment by hughrawlinson** [comment]
Thanks so much Spencer! I'll have the Machine ckdocs PR for you soon :)
