### ISSUE TITLE
Array size vs capacity

### ISSUE THREAD

**Issue by hughrawlinson** [ccrma/chuck#68]
Arrays provide both `size` and `cap` methods. `cap` is used in the examples, `size` is (from what I can tell) not documented. Both of these messages map to a call to `.size()` on the `Chuck_Array` class, which I *think* just returns `m_size`, but I haven't found the exact line for this.

From a documentation perspective, it'd be great to more directly document this functionality, rather than keeping it in examples. I'll make a PR, but I wanted to ask if you have any preference on encouraging people to use `.size()` or `.cap()`, or if I should document them both, noting that one of them may change later (if that's the case)?

Stating the obvious, this is usually something like 'size' or 'length' in other languages, which I would like to note in the documentation for everyone who uses `ctrl+f`.

**Comment by spencersalazar** [comment]
I think `.size()` is encouraged now while `.cap()` was used historically for reasons that Ive since forgotten. To my knowledge they are the same in practice and at this point will probably stay like that given legacy code and documentation.
