### ISSUE TITLE
No audio on Linux

### ISSUE THREAD

**Issue by orchidas** [ccrma/chuck#73]
I installed ChucK on Ubuntu 16.04 (64 bit), and used 'make linux-alsa'. I had to install a few dependencies, but otherwise the installation worked fine. However, when I run any of the scripts, I hear no sound.

P.S - I also installed miniAudicle hoping for different results, but I have the same problem : cannot hear any sound. Please tell me a way around this.

**Comment by orchidas** [comment]
Problem solved. My system uses PulseAudio by default, so I had to remove ChucK and reinstall it with 'make linux-pulse'. I can hear sounds now.

**Comment by spencersalazar** [comment]
Great- glad you got it sorted out 👍
