### ISSUE TITLE
token position is off by one after line comment

### ISSUE THREAD

**Issue by yuanyelele** [ccrma/chuck#95]
``` chuck
// comment
<<< "hello" >>>; #
```

reports:
`[test.ck]:line(2).char(19): syntax error`

should be:
`[test.ck]:line(2).char(18): syntax error`

**Comment by gewang** [comment]
thank you for this report! The parser position tracking was reworked in chuck-1.5.x.x and now produces the expected token position; also now compiler errors when possible come with quoting the source of the error, for example:
```
a.ck:2:18: syntax error
[2] <<< "hello" >>>; #
                     ^
```

**Comment by gewang** [comment]
if you'd like, come hang in the [ChucK Community Discord Server](https://discord.gg/ENr3nurrx8);
check out the latest in ChucK offerings => https://chuck.stanford.edu/
